vessel_discharge_plan:
  send_msg: true
  upload_bay_plan: true
  release_holds: true
  edit_plan: true
  cwp_release: true

vessel_loading_plan:
  create_container:
  release_hold: ture
  work_plan: ture
  cwp_release: ture

gate_pickup_task:
  create_container:
  add_bol: ture
  get_pin: ture
  release_hold: ture
  gate_pickup: ture

gate_ground_task:
  add_return_container:
  gate_ground: true