vessel_discharge_plan:
  send_msg: true
  upload_bay_plan: true
  release_holds: true
  edit_plan: true
  cwp_release: ture

vessel_loading_plan:
  release_hold: true
  work_plan: false
  cwp_release: false

gate_pickup_task:
  create_container: true
  add_bol: true
  get_pin: true
  release_hold: true
  gate_pickup: true

gate_ground_task:
  add_return_container: true
  gate_ground: true